[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://line.me"
    Content-Security-Policy = "frame-ancestors 'self' https://line.me" 